### ISSUE TITLE
Build issues on Ubuntu Quantal i386

### ISSUE THREAD

**Issue by geekpete** [jvasile/freedombox-privoxy#7]
(This was after trying it on Ubuntu Precise, which doesn't work due to an older source version of privoxy in the repos)

I followed the instructions to 'make deb', which failed, I ran it again and:

root@wombat:~/Code/freedombox-privoxy# make deb
./make_deb.sh
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Skipping already downloaded file 'privoxy_3.0.19-2.dsc'
Skipping already downloaded file 'privoxy_3.0.19.orig.tar.gz'
Skipping already downloaded file 'privoxy_3.0.19-2.debian.tar.gz'
Need to get 0 B of source archives.
Skipping unpack of already unpacked source in privoxy-3.0.19
You might need to "apt-get build-dep privoxy" as root
PRIVDIR = privoxy-3.0.19
FBOXDIR = freedombox-privoxy-3.0.19-2-1
DEBDIR = Debian/freedombox-privoxy-3.0.19-2-1
Adding patch config
Adding patch match-all.action
Adding patch default.action
Adding patch default.filter
Adding patch easyprivacy.action
Adding patch easylist.action
Adding patch https_everywhere.action
Adding patch filters.c
Updating changelog
Updating control
Updating rules
~/Code/freedombox-privoxy/Debian/freedombox-privoxy-3.0.19-2-1/debian ~/Code/freedombox-privoxy
~/Code/freedombox-privoxy
Updating doc_base
~/Code/freedombox-privoxy/Debian/freedombox-privoxy-3.0.19-2-1/debian ~/Code/freedombox-privoxy
~/Code/freedombox-privoxy
cd `find Debian -maxdepth 1 -name "freedombox*" -type d`; debuild -us -uc #-kjames@jamesvasile.com
/bin/sh: 1: debuild: not found
make: **\* [debian] Error 127
root@wombat:~/Code/freedombox-privoxy# cd ^C
root@wombat:~/Code/freedombox-privoxy# cd `find Debian -maxdepth 1 -name "freedombox*" -type d`
root@wombat:~/Code/freedombox-privoxy/Debian/freedombox-privoxy-3.0.19-2-1# debuild -us -uc #-kjames@jamesvasile.com
The program 'debuild' is currently not installed. You can install it by typing:
apt-get install devscripts

So installed devscripts and tried again:

make clean
make deb
Traceback (most recent call last):
  File "./https_everywhere_import.py", line 22, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup
make: **\* [privoxy/https_everywhere.action] Error 1

Odd error (seem to fail the first time after a make clean), I changing nothing and ran make deb again and this error doesn't appear and it continues to a further point...

...
~/Code/freedombox-privoxy/Debian/freedombox-privoxy-3.0.19-2-1/debian ~/Code/freedombox-privoxy
~/Code/freedombox-privoxy
Updating doc_base
~/Code/freedombox-privoxy/Debian/freedombox-privoxy-3.0.19-2-1/debian ~/Code/freedombox-privoxy
~/Code/freedombox-privoxy
cd `find Debian -maxdepth 1 -name "freedombox*" -type d`; debuild -us -uc #-kjames@jamesvasile.com
 dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package freedombox-privoxy
dpkg-buildpackage: source version 3.0.19-2-1
dpkg-buildpackage: source changed by James Vasile james@jamesvasile.com
 dpkg-source --before-build freedombox-privoxy-3.0.19-2-1
dpkg-buildpackage: host architecture i386
dpkg-source: info: applying 90_config.dpatch
dpkg-source: info: applying 91_match-all.action.dpatch
dpkg-source: info: applying 92_default.action.dpatch
dpkg-source: info: applying 93_default.filter.dpatch
dpkg-source: info: applying 94_easyprivacy.action.dpatch
dpkg-source: info: applying 95_easylist.action.dpatch
dpkg-source: warning: diff `freedombox-privoxy-3.0.19-2-1/debian/patches/96_https_everywhere.action.dpatch' doesn't contain any patch
dpkg-source: info: applying 96_https_everywhere.action.dpatch
patch: ***\* Only garbage was found in the patch input.
dpkg-source: error: LC_ALL=C patch -t -F 0 -N -p1 -u -V never -g0 -E -b -B .pc/96_https_everywhere.action.dpatch/ --reject-file=- < freedombox-privoxy-3.0.19-2-1/debian/patches/96_https_everywhere.action.dpatch gave error exit status 2
dpkg-source: info: fuzz is not allowed when applying patches
dpkg-source: info: if patch '96_https_everywhere.action.dpatch' is correctly applied by quilt, use 'quilt refresh' to update it
dpkg-buildpackage: error: dpkg-source --before-build freedombox-privoxy-3.0.19-2-1 gave error exit status 2
debuild: fatal error at line 1357:
dpkg-buildpackage -rfakeroot -D -us -uc failed
make: **\* [debian] Error 29
root@wombat:~/Code/freedombox-privoxy#

**Comment by geekpete** [comment]
Some more info...

Some possibly required packages, which made some other errors stop appearing after running make clean; make deb:

apt-get install python-beautifulsoup python-lxml

after installing these and doing make clean, make dep:

Traceback (most recent call last):
  File "./https_everywhere_import.py", line 130, in <module>
    main()
  File "./https_everywhere_import.py", line 123, in main
    for fname in os.listdir(rule_dir):
OSError: [Errno 2] No such file or directory: 'vendor/https-everywhere/src/chrome/content/rules'
make: **\* [privoxy/https_everywhere.action] Error 1

then make dep again gets to the above error again.

**Comment by geekpete** [comment]
Closing as this no longer seems to be active.
